name: "CodeQL"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # Weekly scan on Sunday

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write  # Needed for code scanning results

    strategy:
      fail-fast: false
      matrix:
        language: [ 'c' ]  # Change this to match your codebase (e.g., 'cpp', 'java', etc.)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}

      - name: Build code
        run: |
          gcc -m32 -z execstack -fno-stack-protector vuln-buf-over.c -o vuln
          ./vuln

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
